version: 2
jobs:
  build:
    working_directory: ~/code/sample-case
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
      FASTLANE_LANE: test
    steps:
      - checkout
      - run:
          name: Accept Licenses
          command: yes | sdkmanager --licenses || true
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Download Ruby Dependency
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Download Android Dependencies
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - save_cache:
          paths:
            - vendor/bundle
          key: 1-gems-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build apk
          command: |
            ./gradlew build
      - run:
          name: Fastlane Run Test
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
