version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    docker:
      - image: circleci/android:api-25-alpha
        
    steps:
      - checkout
      - run:
            name: Download Dependencies
            command: sudo chmod +x ./gradlew androidDependencies
      - run:
          command: sudo chmod +x ./gradlew build
