version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    working_directory: ~/samplecase
    executor: android/android

    steps:
      - checkout
      - run:
          command: sudo chmod +x ./gradlew build
