# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build project"
  lane :build do
    gradle(task: "build -x test")
  end

  desc "Download Android Dependencies"
  lane :androidDependencies do
    gradle(task: "androidDependencies")
  end

  desc "Accept licences"
  lane :acceptLicences do
    sh("yes | sdkmanager --licenses || true")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
